---
:queues:
  - login_emails
  - notification_emails
  - mailers
  - default
  - low_priority
  - catch_up_emails
development:
 :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 4 %>
production:
 :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 4 %>
